/* Prewritten sample advice. Nothing here is generated by a model. The Clinical Drafting
   preview selects from approved wording and fills it from the episode's own flags. A
   clinician edits and approves it. It never diagnoses, invents values or decides urgency. */
export const ADVICE_ROUTINE = [
  "Your results are within the illustrative ranges shown in this sample report. Keep up regular physical activity and a balanced diet. Sample content for demonstration.",
  "Sample advice: results sit within the displayed illustrative ranges. Continue regular activity, limit processed foods and have a routine check in a year. Demonstration content only.",
  "Sample advice: nothing in this report is marked for review. Maintain current habits and stay active. Demonstration content only.",
  "Sample advice: all displayed results are within the illustrative ranges. A balanced diet and regular movement are encouraged. Demonstration content only.",
];
export const ADVICE_FLAGGED = [
  "Sample advice: one or more results are marked for clinician review. Please discuss this report with your GP at your next visit. Demonstration content only.",
  "Sample advice: some displayed values are outside the illustrative ranges. Your GP can advise on next steps. Demonstration content only.",
];

/** Deterministic Clinical Drafting preview from approved wording and the episode's own flag labels. */
export function aiDraftFor(flagLabels: string[], pending: string[]): string {
  const lines = [
    "Draft for clinician review. Demo content, no model connected.",
    flagLabels.length
      ? `This report marks ${flagLabels.join(", ")} for clinician review against the displayed illustrative limits. Please discuss it with your GP at your next visit.`
      : "All displayed results are within the illustrative ranges shown in this sample report.",
    pending.length ? `These expected tests are not yet accounted for and are not described here: ${pending.join(", ")}.` : "",
    "General lifestyle wording: regular physical activity and a balanced diet are encouraged.",
  ];
  return lines.filter(Boolean).join("\n\n");
}
